import Head from 'next/head';
// import styles from '@/styles/Home.module.css';
import classes from '../styles/Home.module.css';
import Link from 'next/link';

export default function Home() {
  return (
    <div className={classes.loginSection}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className={classes.loginParentContainer}>
          <div className={classes.loginChildContainer}>
            <h2 className={classes.welcomeMessage}>FlipR Hackathon</h2>
            <p className={classes.welcomeMessage}>Lets Start with FlipR</p>
            <div>
              <Link href='/login'>
                <button type='submit' >Login</button>
              </Link>
              <Link href='/register'>
                <button type='submit' >Signup</button>
              </Link>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}